/* ============================================================
   Daftar isi buku. Tinggal tambah entri di sini kalau bikin
   pelajaran baru — file .md-nya taruh di content/<lang>/.
   "mark" = monogram badge (pengganti emoji), "color" = aksennya.
   ============================================================ */

const BOOK = [
  {
    id: "python",
    nama: "Python",
    mark: "Py",
    color: "#3776ab",
    logo: "aset/logos/python.svg",
    deskripsi: "Bahasa serbaguna & mudah dibaca. Favorit untuk AI, data science, dan web backend.",
    pelajaran: [
      { id: "01-pengenalan", judul: "1. Pengenalan Python" },
      { id: "02-variabel-tipe", judul: "2. Variabel & Tipe Data" },
      { id: "03-operator", judul: "3. Operator" },
      { id: "08-string", judul: "4. String (Teks)" },
      { id: "04-kontrol-alur", judul: "5. Percabangan & Perulangan" },
      { id: "06-struktur-data", judul: "6. List, Dict, Tuple, Set" },
      { id: "05-fungsi", judul: "7. Fungsi" },
      { id: "07-oop", judul: "8. OOP Dasar" },
      { id: "09-oop-lanjutan", judul: "9. OOP Lanjutan" },
      { id: "10-error-handling", judul: "10. Error Handling" },
      { id: "11-comprehension", judul: "11. Comprehension & Generator" },
      { id: "12-modul", judul: "12. Modul & Package" },
      { id: "13-file-io", judul: "13. File & JSON" },
      { id: "14-decorator", judul: "14. Decorator & Context Manager" },
      { id: "15-type-hints", judul: "15. Type Hints & Dataclass" },
      { id: "16-library", judul: "16. Library Populer & pip" },
      { id: "17-best-practices", judul: "17. Best Practices" },
    ],
  },
  {
    id: "javascript",
    nama: "JavaScript",
    mark: "JS",
    color: "#c99a06",
    logo: "aset/logos/javascript.svg",
    deskripsi: "Bahasa web & fondasi React. Materi difokuskan ke JavaScript modern (ES6+) yang dipakai membangun aplikasi React.",
    pelajaran: [
      { id: "01-pengenalan", judul: "1. Pengenalan JavaScript" },
      { id: "02-variabel-tipe", judul: "2. Variabel & Tipe Data" },
      { id: "03-operator", judul: "3. Operator" },
      { id: "04-string", judul: "4. String & Template Literal" },
      { id: "05-kontrol-alur", judul: "5. Percabangan & Perulangan" },
      { id: "06-fungsi", judul: "6. Fungsi & Arrow Function" },
      { id: "07-array", judul: "7. Array & Method Penting" },
      { id: "08-object", judul: "8. Object" },
      { id: "09-destructuring", judul: "9. Destructuring, Spread & Rest" },
      { id: "10-modules", judul: "10. ES Modules (import/export)" },
      { id: "11-async", judul: "11. Async: Promise & await" },
      { id: "12-error-handling", judul: "12. Error Handling (try/catch)" },
      { id: "13-closure-hof", judul: "13. Closure & Higher-Order Function" },
      { id: "14-this-class", judul: "14. this & Class" },
      { id: "15-dom-events", judul: "15. DOM & Events" },
      { id: "16-modern-react", judul: "16. JavaScript Modern untuk React" },
    ],
  },
  {
    id: "react",
    nama: "React",
    mark: "Re",
    color: "#087ea4",
    logo: "aset/logos/react.svg",
    deskripsi: "Library JavaScript untuk membangun antarmuka web. Materi lengkap & mendalam, dari instalasi sampai hooks, sesuai proyek React sungguhan.",
    pelajaran: [
      { id: "01-instalasi", judul: "1. Instalasi & Setup Proyek" },
      { id: "02-jsx", judul: "2. JSX" },
      { id: "03-komponen-props", judul: "3. Komponen & Props" },
      { id: "04-usestate", judul: "4. State dengan useState" },
      { id: "05-events-form", judul: "5. Event & Form" },
      { id: "06-list-kondisional", judul: "6. Rendering Daftar & Kondisional" },
      { id: "07-useeffect", judul: "7. useEffect & Lifecycle" },
      { id: "08-data-fetching", judul: "8. Mengambil Data (Fetch & Supabase)" },
      { id: "09-usecontext", judul: "9. useContext (State Global)" },
      { id: "10-custom-hooks", judul: "10. Custom Hooks" },
      { id: "11-router", judul: "11. React Router" },
      { id: "12-library", judul: "12. Library Ekosistem React" },
      { id: "13-best-practices", judul: "13. Best Practices & Struktur Proyek" },
    ],
  },
  {
    id: "cpp",
    nama: "C++",
    mark: "C++",
    color: "#8a4fa3",
    logo: "aset/logos/cpp.svg",
    deskripsi: "Bahasa cepat & dekat dengan mesin. Untuk game, sistem, dan kompetisi programming.",
    pelajaran: [
      { id: "01-pengenalan", judul: "1. Pengenalan C++" },
      { id: "02-variabel-tipe", judul: "2. Variabel & Tipe Data" },
      { id: "03-kontrol-alur", judul: "3. Percabangan & Perulangan" },
      { id: "04-fungsi", judul: "4. Fungsi" },
      { id: "05-pointer", judul: "5. Pointer & Referensi" },
    ],
  },
  {
    id: "php",
    nama: "PHP",
    mark: "php",
    color: "#6a7bb0",
    logo: "aset/logos/php.svg",
    deskripsi: "Bahasa web server klasik. Menggerakkan banyak situs (WordPress, Laravel).",
    pelajaran: [
      { id: "01-pengenalan", judul: "1. Pengenalan PHP" },
      { id: "02-dasar", judul: "2. Variabel & Dasar Sintaks" },
    ],
  },
  {
    id: "go",
    nama: "Go",
    mark: "Go",
    color: "#2a9fb8",
    logo: "aset/logos/go.svg",
    deskripsi: "Bahasa modern dari Google. Cepat, sederhana, andal untuk server & cloud.",
    pelajaran: [
      { id: "01-pengenalan", judul: "1. Pengenalan Go" },
      { id: "02-dasar", judul: "2. Variabel & Dasar Sintaks" },
    ],
  },
];
